GitVersion version 0.9.3 specified instead of 0.9
Fixing issues.
1) "Value '' cannot be parsed as output type, please use 'json', 'file' or 'buildserver'"
2) "(node:2664) UnhandledPromiseRejectionWarning: TypeError: (e || "").replace is not a function"
According to the link https://github.com/GitTools/actions/issues/76